name: Cloudflared

on:
  workflow_dispatch:
  # 可以添加其他触发条件，例如 schedule 或 push

jobs:
  setup-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Script
        run: sudo chmod +x install_v2ray.sh && sudo ./install_v2ray.sh  # 给脚本执行权限并运行

      - name: Check service
        run: sudo systemctl status v2ray  # 检查服务状态

      - name: Pull cloudflared image
        run: docker pull cloudflare/cloudflared:latest

      - name: Run cloudflared tunnel
        run: |
          docker run -d --name cloudflared-tunnel cloudflare/cloudflared:latest tunnel --no-autoupdate run \
          --token eyJhIjoiMDZhMGFjODg4ODkzZTBkMDdlZDg4N2QyMDk2YTFhNjMiLCJ0IjoiOGFkYzZkZjAtZDFkNi00ODBkLTk4MzMtYjUzNTY4Mjg4ZTVkIiwicyI6IlpUUmhZVEkxWkRBdFpUTTJNQzAwT1dSaExUaGxObU10TldKaU0yVmhNbVpsTlRBeiJ9

      - name: Check tunnel status
        run: |
          sleep 3600
          docker logs cloudflared-tunnel
