name: SSH with Ngrok

on: 
  workflow_dispatch:  # 也可以手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SSH Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo service ssh start

      - name: Setup Ngrok Tunnel and Auto-Restart
        run: |
          # 添加 ngrok 的官方 GPG 密钥
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null

          # 添加 ngrok 的官方 APT 源
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list

          # 更新 APT 包列表并安装 ngrok
          sudo apt update && sudo apt install ngrok

          # 验证 ngrok 版本
          ngrok version
      
          # 启动 ngrok 并每 60 分钟重启一次
          for ((i=0; i<4; i++)); do
            echo "Starting ngrok tunnel for 60 minutes... ${{ vars.NGROK_TOKEN }}"
            ngrok tcp 18524 --authtoken ${{ vars.NGROK_TOKEN }} --log=stdout &
      
            # 等待 60 分钟
            sleep 3600
      
            echo "Restarting ngrok tunnel..."
            pkill -f ngrok
          done
